In [ ]:
import numpy as np

In [31]:
#задание1
n=10
np.arange(n,-1,-1)


array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [32]:
#Задание2
n=10
np.diag(np.arange(n,-1,-1))

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [33]:
#Задание5
from numpy import linalg
a=np.array([[4,2,1],[1,3,0],[0,5,4]])
b=np.array([4,12,-3])
linalg.solvelve(a,b)




array([ 0.46666667,  3.84444444, -5.55555556])

In [63]:
#Задание3
import pandas as pd
#pd.read_html('http://files.grouplens.org/datasets/movielens/ml-latest-small.zip')
data = pd.read_csv('ml-latest/ratings.csv')
data[data.rating == 5.0].groupby('movieId').count().sort_values('rating', ascending=False).head()

userId  rating  timestamp
movieId                           
318         153     153        153
296         123     123        123
356         116     116        116
2571        109     109        109
260         104     104        104

In [111]:
#Задание4
import pandas as pd
#pd.read_html('http://files.grouplens.org/datasets/movielens/ml-latest-small.zip')
data = pd.read_csv('6/power.csv')
df1=data[((data['year']>2004) & (data['year']<2011)) & ((data.category == 4) | (data.category == 12) | (data.category == 21) )]
df1[(df1.country=='Latvia') | (df1.country=='Lithuania') | (df1.country=='Estonia')].groupby('country').count().head()

year  quantity  category
country                            
Estonia      99        99        99
Latvia       92        92        92
Lithuania   220       220       220

In [107]:
data.country.unique()Латвия, Литва и Эстония Lithuania Estonia

array(['Austria', 'Belgium', 'Czechia', 'Finland', 'France', 'Greece',
       'Hungary', 'Italy', 'Korea, Republic of', 'Netherlands', 'Romania',
       'Serbia', 'Slovakia', 'Ukraine', 'United Kingdom', 'United States',
       'Brunei Darussalam', 'Bulgaria', 'Canada', 'Chile', 'Croatia',
       'Iran (Islamic Rep. of)', 'Jordan', 'Lithuania', 'Mexico', 'Oman',
       'Other Asia', 'Poland', 'Portugal', 'Spain', 'Sweden',
       'Switzerland', 'T.F.Yug.Rep. Macedonia', 'Turkey', 'Uzbekistan',
       'Argentina', 'Colombia', 'Germany', 'Norway', 'Australia',
       'China, Macao SAR', 'Japan', 'Denmark', 'Ireland', 'Philippines',
       'Bangladesh', 'Eritrea', 'Ethiopia', 'Lesotho', 'Nepal', 'Niger',
       'Pakistan', 'Serbia and Montenegro', 'Tunisia', 'Botswana',
       'Georgia', 'Republic of Moldova', 'Peru', 'South Africa',
       'Iceland', 'Latvia', 'Luxembourg', 'Cuba', 'Kyrgyzstan',
       'Singapore', 'Thailand', 'United Arab Emirates', 'Uruguay',
       'Armenia', 'Fiji', 